-- =============================================================================
-- [0] 기존 테이블 전체 삭제 (초기화)
-- =============================================================================
DROP TABLE CHAT_MESSAGE CASCADE CONSTRAINTS;
DROP TABLE CHAT_INQUIRY CASCADE CONSTRAINTS;
DROP TABLE FAVORITE_ROUTE CASCADE CONSTRAINTS;
DROP TABLE REFUND CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE TICKET CASCADE CONSTRAINTS;
DROP TABLE BOOKING_PASSENGER CASCADE CONSTRAINTS;
DROP TABLE BOOKING CASCADE CONSTRAINTS;
DROP TABLE SAVED_PASSENGER CASCADE CONSTRAINTS;
DROP TABLE FAQ CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE FLIGHT_NOTICE CASCADE CONSTRAINTS;
DROP TABLE FLIGHT_FARE CASCADE CONSTRAINTS;
DROP TABLE FLIGHT CASCADE CONSTRAINTS;
DROP TABLE FARE CASCADE CONSTRAINTS;
DROP TABLE SEAT CASCADE CONSTRAINTS;
DROP TABLE AIRCRAFT CASCADE CONSTRAINTS;
DROP TABLE ROUTE CASCADE CONSTRAINTS;
DROP TABLE GATE CASCADE CONSTRAINTS;
DROP TABLE AIRPORT CASCADE CONSTRAINTS;
DROP TABLE NOTIFICATION CASCADE CONSTRAINTS;
DROP TABLE SEASON CASCADE CONSTRAINTS;
DROP TABLE SEAT_CLASS CASCADE CONSTRAINTS;
DROP TABLE ROUTE_TYPE CASCADE CONSTRAINTS;
DROP TABLE GATE_AREA CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;
--DROP TABLE MEMBER CASCADE CONSTRAINTS;

-- =============================================================================
-- [1] 공통 및 시스템 관리자 (의존성 없는 마스터 테이블)
-- =============================================================================

-- 1. 회원 (MEMBER)
--CREATE TABLE MEMBER (
--    member_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    login_id VARCHAR2(50) NOT NULL UNIQUE,
--    password VARCHAR2(255) NOT NULL,
--    name VARCHAR2(50) NOT NULL,
--    email VARCHAR2(100) UNIQUE,
--    phone VARCHAR2(20) UNIQUE,
--    zipcode VARCHAR2(5) NOT NULL,
--    address1 VARCHAR2(120) NOT NULL,
--    address2 VARCHAR2(90) NOT NULL,
--    role VARCHAR2(20) DEFAULT 'USER' NOT NULL CHECK (role IN ('USER', 'STAFF', 'ADMIN')),
--    status VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DELETED', 'INACTIVE')),
--    suspend_reason VARCHAR2(200),
--    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
--    updated_at TIMESTAMP
--);

-- 2. 권역 (REGION)
CREATE TABLE REGION (
    region_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_name VARCHAR2(50) NOT NULL UNIQUE,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N'))
);

-- 3. 게이트 구역 (GATE_AREA)
CREATE TABLE GATE_AREA (
    gate_area_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_name VARCHAR2(50) NOT NULL UNIQUE,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N'))
);

-- 4. 노선 유형 (ROUTE_TYPE)
CREATE TABLE ROUTE_TYPE (
    route_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR2(50) NOT NULL UNIQUE,
    route_price NUMBER NOT NULL,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N'))
);

-- 5. 좌석 등급 (SEAT_CLASS)
-- ROWS, COLUMNS는 오라클 예약어이므로 쌍따옴표(") 처리하여 컬럼명으로 명시
CREATE TABLE SEAT_CLASS (
    seat_class_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name VARCHAR2(50) NOT NULL UNIQUE,
    class_ratio NUMBER(4,2) DEFAULT 1.0 NOT NULL CHECK (class_ratio > 0), --추가
    sort_order NUMBER(3) NOT NULL UNIQUE
);

-- 6. 시즌 (SEASON)
CREATE TABLE SEASON (
    season_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_name VARCHAR2(50) NOT NULL UNIQUE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    season_ratio NUMBER NOT NULL,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT chk_season_dates CHECK (end_date >= start_date)
);

-- 7. 알림 (NOTIFICATION)
CREATE TABLE NOTIFICATION (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    type VARCHAR2(30) NOT NULL,
    content VARCHAR2(500) NOT NULL,
    ref_type VARCHAR2(20),
    ref_url VARCHAR2(100),
    is_read CHAR(1) DEFAULT 'N' NOT NULL CHECK (is_read IN ('Y', 'N')),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_notification_member FOREIGN KEY (member_id) REFERENCES MEMBER(member_id)
);


-- =============================================================================
-- [2] 지상직 (운항 및 기준정보)
-- =============================================================================

-- 8. 공항 (AIRPORT)
CREATE TABLE AIRPORT (
    airport_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iata_code CHAR(3) NOT NULL UNIQUE,
    airport_name VARCHAR2(100) NOT NULL,
    country VARCHAR2(50) NOT NULL,
    timezone VARCHAR2(40) NOT NULL,
    region_id NUMBER NOT NULL,
    flight_type VARCHAR2(3) NOT NULL CHECK (flight_type IN ('DOM', 'INT')),
    is_active CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT chk_airport_iata CHECK (REGEXP_LIKE(iata_code, '^[A-Z]{3}$')),
    CONSTRAINT fk_airport_region FOREIGN KEY (region_id) REFERENCES REGION(region_id)
);

-- 9. 게이트 (GATE)
CREATE TABLE GATE (
    gate_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airport_id NUMBER NOT NULL,
    gate_code VARCHAR2(10) NOT NULL,
    gate_area_id NUMBER NOT NULL,
    flight_type VARCHAR2(3) NOT NULL CHECK (flight_type IN ('DOM', 'INT')),
    is_active CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT uq_gate_airport_code UNIQUE (airport_id, gate_code),
    CONSTRAINT fk_gate_airport FOREIGN KEY (airport_id) REFERENCES AIRPORT(airport_id),
    CONSTRAINT fk_gate_area FOREIGN KEY (gate_area_id) REFERENCES GATE_AREA(gate_area_id)
);

-- 10. 노선 (ROUTE)
CREATE TABLE ROUTE (
    route_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departure_airport_id NUMBER NOT NULL,
    arrival_airport_id NUMBER NOT NULL,
    flight_type VARCHAR2(3) NOT NULL CHECK (flight_type IN ('DOM', 'INT')),
    route_type_id NUMBER NOT NULL,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT fk_route_dept_airport FOREIGN KEY (departure_airport_id) REFERENCES AIRPORT(airport_id),
    CONSTRAINT fk_route_arrv_airport FOREIGN KEY (arrival_airport_id) REFERENCES AIRPORT(airport_id),
    CONSTRAINT fk_route_type FOREIGN KEY (route_type_id) REFERENCES ROUTE_TYPE(route_type_id),
    CONSTRAINT chk_route_airports CHECK (departure_airport_id != arrival_airport_id)
);

-- 11. 항공기 (AIRCRAFT)
CREATE TABLE AIRCRAFT (
    aircraft_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reg_no VARCHAR2(20) NOT NULL UNIQUE,
    model_name VARCHAR2(50) NOT NULL,
    total_seats NUMBER(4) NOT NULL CHECK (total_seats >= 1),
    status_name VARCHAR2(50) DEFAULT '운항가능' NOT NULL CHECK (status_name IN ('운항가능', '정비중', '퇴역')),
    is_active CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N'))
);

-- 12. 좌석 (SEAT)
CREATE TABLE SEAT (
    seat_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aircraft_id NUMBER NOT NULL,
    seat_no VARCHAR2(5) NOT NULL,
    seat_class_id NUMBER NOT NULL,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT uq_seat_aircraft_no UNIQUE (aircraft_id, seat_no),
    CONSTRAINT fk_seat_aircraft FOREIGN KEY (aircraft_id) REFERENCES AIRCRAFT(aircraft_id),
    CONSTRAINT fk_seat_class FOREIGN KEY (seat_class_id) REFERENCES SEAT_CLASS(seat_class_id)
);

-- 13. 운임 (FARE)
CREATE TABLE FARE (
    fare_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id NUMBER NOT NULL,
    seat_class_id NUMBER NOT NULL,
    season_id NUMBER NOT NULL,
    price NUMBER(10) NOT NULL CHECK (price > 0),
    is_active CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT fk_fare_route FOREIGN KEY (route_id) REFERENCES ROUTE(route_id),
    CONSTRAINT fk_fare_seat_class FOREIGN KEY (seat_class_id) REFERENCES SEAT_CLASS(seat_class_id),
    CONSTRAINT fk_fare_season FOREIGN KEY (season_id) REFERENCES SEASON(season_id),
    CONSTRAINT uq_fare_rule UNIQUE (route_id, seat_class_id, season_id)
);

-- 14. 운항 스케줄 (FLIGHT)
CREATE TABLE FLIGHT (
    flight_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_no VARCHAR2(10) NOT NULL,
    route_id NUMBER NOT NULL,
    aircraft_id NUMBER NOT NULL,
    departure_gate_id NUMBER,
    arrival_gate_id NUMBER,
    departure_time TIMESTAMP NOT NULL,
    arrival_time TIMESTAMP NOT NULL,
    flight_status VARCHAR2(15) DEFAULT 'SCHEDULED' NOT NULL 
        CHECK (flight_status IN ('SCHEDULED', 'BOARDING', 'DEPARTED', 'ARRIVED', 'DELAYED', 'CANCELLED', 'COMPLETED')),
    delay_minutes NUMBER(5),
    is_deleted CHAR(1) DEFAULT 'N' NOT NULL CHECK (is_deleted IN ('Y', 'N')),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT uq_flight_no_date UNIQUE (flight_no, departure_time),
    CONSTRAINT chk_flight_times CHECK (arrival_time > departure_time),
    CONSTRAINT chk_flight_delay CHECK (delay_minutes >= 0),
    CONSTRAINT fk_flight_route FOREIGN KEY (route_id) REFERENCES ROUTE(route_id),
    CONSTRAINT fk_flight_aircraft FOREIGN KEY (aircraft_id) REFERENCES AIRCRAFT(aircraft_id),
    CONSTRAINT fk_flight_dept_gate FOREIGN KEY (departure_gate_id) REFERENCES GATE(gate_id),
    CONSTRAINT fk_flight_arrv_gate FOREIGN KEY (arrival_gate_id) REFERENCES GATE(gate_id)
);

-- 15. 항공편 운임 (FLIGHT_FARE)
CREATE TABLE FLIGHT_FARE (
    flight_fare_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id NUMBER NOT NULL,
    seat_class_id NUMBER NOT NULL,
    fare_id NUMBER NOT NULL,
    price NUMBER(10) NOT NULL CHECK (price > 0),
    CONSTRAINT uq_flight_fare_class UNIQUE (flight_id, seat_class_id),
    CONSTRAINT fk_flight_fare_flight FOREIGN KEY (flight_id) REFERENCES FLIGHT(flight_id),
    CONSTRAINT fk_flight_fare_class FOREIGN KEY (seat_class_id) REFERENCES SEAT_CLASS(seat_class_id),
    CONSTRAINT fk_flight_fare_id FOREIGN KEY (fare_id) REFERENCES FARE(fare_id)
);

-- 16. 지연/결항 안내 (FLIGHT_NOTICE)
CREATE TABLE FLIGHT_NOTICE (
    flight_notice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id NUMBER NOT NULL,
    notice_type VARCHAR2(10) NOT NULL CHECK (notice_type IN ('DELAY', 'CANCEL')),
    reason VARCHAR2(500) NOT NULL,
    delay_minutes NUMBER(5),
    created_by NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_flight_notice_flight FOREIGN KEY (flight_id) REFERENCES FLIGHT(flight_id),
    CONSTRAINT fk_flight_notice_maker FOREIGN KEY (created_by) REFERENCES MEMBER(member_id)
);

-- 17. 공지사항 (NOTICE)
CREATE TABLE NOTICE (
    notice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR2(30) DEFAULT 'ETC' NOT NULL
        CHECK (
            category IN (
                'SKY_NEWS',
                'FUEL_SURCHARGE',
                'MEMBERSHIP_CLUB',
                'PARTNER_NEWS',
                'ETC'
            )
        ),
    title VARCHAR2(200) NOT NULL,
    content CLOB NOT NULL,
    is_public CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_public IN ('Y', 'N')),
    created_by NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_notice_maker FOREIGN KEY (created_by) REFERENCES MEMBER(member_id)
);

-- 18. 이벤트 (EVENT)
CREATE TABLE EVENT (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    content CLOB NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    image_url VARCHAR2(500),
    is_visible CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_visible IN ('Y', 'N')),
    is_ended CHAR(1) DEFAULT 'N' NOT NULL CHECK (is_ended IN ('Y', 'N')),
    created_by NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_event_dates CHECK (end_date >= start_date),
    CONSTRAINT fk_event_maker FOREIGN KEY (created_by) REFERENCES MEMBER(member_id)
);

-- 19. 자주 묻는 질문 (FAQ)
CREATE TABLE FAQ (
    faq_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR2(30) NOT NULL,
    question VARCHAR2(300) NOT NULL,
    answer CLOB NOT NULL,
    is_visible CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_visible IN ('Y', 'N')),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    priority_num NUMBER DEFAULT 0 NOT NULL
);


-- =============================================================================
-- [3] 사용자 (예약 및 결제)
-- =============================================================================

-- 20. 등록 탑승객 (SAVED_PASSENGER)
CREATE TABLE SAVED_PASSENGER (
    saved_passenger_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    name VARCHAR2(50) NOT NULL,
    birth_date DATE NOT NULL,
    phone VARCHAR2(20),
    gender CHAR(1) CHECK (gender IN ('M', 'F')),
    passport_no VARCHAR2(20),
    passport_expiry DATE,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_saved_pass_member FOREIGN KEY (member_id) REFERENCES MEMBER(member_id)
);

-- 21. 예약 (BOOKING)
CREATE TABLE BOOKING (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_no VARCHAR2(20) NOT NULL UNIQUE,
    member_id NUMBER NOT NULL,
    trip_type VARCHAR2(10) NOT NULL CHECK (trip_type IN ('ONEWAY', 'ROUNDTRIP')),
    outbound_flight_id NUMBER NOT NULL,
    inbound_flight_id NUMBER,
    status VARCHAR2(10) DEFAULT 'PENDING' NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'FAILED')),
    total_amount NUMBER(12) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    cancelled_at TIMESTAMP,
    CONSTRAINT fk_booking_member FOREIGN KEY (member_id) REFERENCES MEMBER(member_id),
    CONSTRAINT fk_booking_outbound FOREIGN KEY (outbound_flight_id) REFERENCES FLIGHT(flight_id),
    CONSTRAINT fk_booking_inbound FOREIGN KEY (inbound_flight_id) REFERENCES FLIGHT(flight_id),
    CONSTRAINT chk_booking_trip_type CHECK (
        (trip_type = 'ONEWAY' AND inbound_flight_id IS NULL) OR 
        (trip_type = 'ROUNDTRIP' AND inbound_flight_id IS NOT NULL)
    )
);

-- 22. 동승자 (BOOKING_PASSENGER)
CREATE TABLE BOOKING_PASSENGER (
    booking_passenger_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id NUMBER NOT NULL,
    saved_passenger_id NUMBER,
    name VARCHAR2(50) NOT NULL,
    birth_date DATE NOT NULL,
    phone VARCHAR2(20),
    gender CHAR(1) CHECK (gender IN ('M', 'F')),
    passport_no VARCHAR2(20),
    passport_expiry DATE,
    CONSTRAINT fk_bk_pass_booking FOREIGN KEY (booking_id) REFERENCES BOOKING(booking_id),
    CONSTRAINT fk_bk_pass_saved FOREIGN KEY (saved_passenger_id) REFERENCES SAVED_PASSENGER(saved_passenger_id)
);

-- 23. 티켓 (TICKET)
CREATE TABLE TICKET (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id NUMBER NOT NULL,
    booking_passenger_id NUMBER NOT NULL,
    flight_id NUMBER NOT NULL,
    seat_id NUMBER NOT NULL,
    leg_type VARCHAR2(10) NOT NULL CHECK (leg_type IN ('OUTBOUND', 'INBOUND')),
    fare_amount NUMBER(10) NOT NULL,
    hold_status VARCHAR2(10) DEFAULT 'HOLDING' NOT NULL 
        CHECK (hold_status IN ('HOLDING', 'CONFIRMED', 'RELEASED', 'CANCELLED')),
    held_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    expired_at TIMESTAMP,
    checkin_status VARCHAR2(15) DEFAULT 'NOT_CHECKED_IN' NOT NULL 
        CHECK (checkin_status IN ('NOT_CHECKED_IN', 'CHECKED_IN', 'BOARDED', 'NO_SHOW')),
    checked_in_at TIMESTAMP,
    checked_in_by NUMBER,
    boarded_at TIMESTAMP,
    boarded_by NUMBER,
    CONSTRAINT fk_ticket_booking FOREIGN KEY (booking_id) REFERENCES BOOKING(booking_id),
    CONSTRAINT fk_ticket_bk_pass FOREIGN KEY (booking_passenger_id) REFERENCES BOOKING_PASSENGER(booking_passenger_id),
    CONSTRAINT fk_ticket_flight FOREIGN KEY (flight_id) REFERENCES FLIGHT(flight_id),
    CONSTRAINT fk_ticket_seat FOREIGN KEY (seat_id) REFERENCES SEAT(seat_id),
    CONSTRAINT fk_ticket_chk_staff FOREIGN KEY (checked_in_by) REFERENCES MEMBER(member_id),
    CONSTRAINT fk_ticket_brd_staff FOREIGN KEY (boarded_by) REFERENCES MEMBER(member_id)
);

-- 24. 결제 (PAYMENT)
CREATE TABLE PAYMENT (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id NUMBER NOT NULL,
    method VARCHAR2(20) NOT NULL CHECK (method IN ('KAKAOPAY', 'CARD', 'VBANK')),
    amount NUMBER(12) NOT NULL,
    status VARCHAR2(16) DEFAULT 'READY' NOT NULL 
        CHECK (status IN ('READY', 'PAID', 'FAILED', 'CANCELLED', 'PARTIAL_REFUNDED', 'REFUNDED')),
    imp_uid VARCHAR2(50) UNIQUE,
    merchant_uid VARCHAR2(50) UNIQUE,
    paid_at TIMESTAMP,
    refund_amount NUMBER(12),
    refunded_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES BOOKING(booking_id)
);

-- 25. 환불 (REFUND)
CREATE TABLE REFUND (
    refund_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id NUMBER NOT NULL,
    ticket_id NUMBER NOT NULL UNIQUE,
    amount NUMBER(10) NOT NULL CHECK (amount > 0),
    reason VARCHAR2(200),
    refunded_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_refund_payment FOREIGN KEY (payment_id) REFERENCES PAYMENT(payment_id),
    CONSTRAINT fk_refund_ticket FOREIGN KEY (ticket_id) REFERENCES TICKET(ticket_id)
);

-- 26. 관심 노선 (FAVORITE_ROUTE)
CREATE TABLE FAVORITE_ROUTE (
    favorite_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    favorite_type VARCHAR2(10) NOT NULL CHECK (favorite_type IN ('ROUTE', 'FLIGHT')),
    departure_airport_id NUMBER,
    arrival_airport_id NUMBER,
    flight_id NUMBER,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_favorite_combination UNIQUE (member_id, departure_airport_id, arrival_airport_id, flight_id),
    CONSTRAINT fk_fav_member FOREIGN KEY (member_id) REFERENCES MEMBER(member_id),
    CONSTRAINT fk_fav_dept_airport FOREIGN KEY (departure_airport_id) REFERENCES AIRPORT(airport_id),
    CONSTRAINT fk_fav_arrv_airport FOREIGN KEY (arrival_airport_id) REFERENCES AIRPORT(airport_id),
    CONSTRAINT fk_fav_flight FOREIGN KEY (flight_id) REFERENCES FLIGHT(flight_id),
    CONSTRAINT chk_favorite_type_data CHECK (
        (favorite_type = 'ROUTE' AND departure_airport_id IS NOT NULL AND arrival_airport_id IS NOT NULL AND flight_id IS NULL) OR
        (favorite_type = 'FLIGHT' AND flight_id IS NOT NULL AND departure_airport_id IS NULL AND arrival_airport_id IS NULL)
    )
);

-- 27. 채팅 문의 (CHAT_INQUIRY)
CREATE TABLE CHAT_INQUIRY (
    inquiry_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    staff_id NUMBER,
    status VARCHAR2(15) DEFAULT 'IN_PROGRESS' NOT NULL CHECK (status IN ('IN_PROGRESS', 'RESOLVED')),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    CONSTRAINT fk_chat_member FOREIGN KEY (member_id) REFERENCES MEMBER(member_id),
    CONSTRAINT fk_chat_staff FOREIGN KEY (staff_id) REFERENCES MEMBER(member_id)
);

-- 28. 채팅 메시지 (CHAT_MESSAGE)
CREATE TABLE CHAT_MESSAGE (
    message_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_id NUMBER NOT NULL,
    sender_id NUMBER NOT NULL,
    sender_type VARCHAR2(10) NOT NULL CHECK (sender_type IN ('USER', 'STAFF')),
    content VARCHAR2(2000) NOT NULL,
    sent_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_msg_inquiry FOREIGN KEY (inquiry_id) REFERENCES CHAT_INQUIRY(inquiry_id),
    CONSTRAINT fk_msg_sender FOREIGN KEY (sender_id) REFERENCES MEMBER(member_id)
);


--NOTICE 테이블 category 칼럼 추가
ALTER TABLE NOTICE ADD category VARCHAR2(30) DEFAULT 'ETC';

UPDATE NOTICE
SET category = 'ETC'
WHERE category IS NULL;

ALTER TABLE NOTICE MODIFY category NOT NULL;

ALTER TABLE NOTICE ADD CONSTRAINT chk_notice_category
CHECK (
    category IN (
        'SKY_NEWS',
        'FUEL_SURCHARGE',
        'MEMBERSHIP_CLUB',
        'PARTNER_NEWS',
        'ETC'
    )
);

-- EVENT 테이블 추첨 컬럼 보정 
ALTER TABLE EVENT ADD (
    RESULT_STATUS       VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    RESULT_ANNOUNCED_AT TIMESTAMP
);

-- 기존 EVENT 행 기본값 보정 (DEFAULT 는 신규 행에만 적용됨)
UPDATE EVENT SET RESULT_STATUS = 'PENDING' WHERE RESULT_STATUS IS NULL;

-- (선택) 상태값 무결성. 담당자 상태 정의와 다르면 값만 조정.
ALTER TABLE EVENT ADD CONSTRAINT chk_event_result_status
    CHECK (RESULT_STATUS IN ('PENDING', 'ANNOUNCED'));

COMMIT;

ALTER TABLE EVENT ADD (
    DISPLAY_ORDER NUMBER DEFAULT 0 NOT NULL,
    WINNER_COUNT  NUMBER DEFAULT 0 NOT NULL
);

-- 기존 행 기본값 보정 (DEFAULT 는 신규 행에만 적용됨)
UPDATE EVENT SET DISPLAY_ORDER = 0 WHERE DISPLAY_ORDER IS NULL;
UPDATE EVENT SET WINNER_COUNT  = 0 WHERE WINNER_COUNT  IS NULL;

ALTER TABLE BOOKING_PASSENGER ADD (
    passenger_type VARCHAR2(10) DEFAULT 'ADULT' NOT NULL
        CHECK (passenger_type IN ('ADULT', 'CHILD', 'INFANT'))
);

CREATE UNIQUE INDEX uq_ticket_active_seat ON TICKET (
    CASE WHEN hold_status IN ('HOLDING', 'CONFIRMED') THEN flight_id END,
    CASE WHEN hold_status IN ('HOLDING', 'CONFIRMED') THEN seat_id   END
);

CREATE INDEX idx_ticket_flight_status ON TICKET (flight_id, hold_status);
CREATE INDEX idx_ticket_booking       ON TICKET (booking_id);
CREATE INDEX idx_booking_member       ON BOOKING (member_id, created_at DESC);
 
-- HOLD 만료 스케줄러가 매분 스캔하는 조건
CREATE INDEX idx_ticket_expired ON TICKET (hold_status, expired_at);
 

COMMIT;