spring.mail.host=test
spring.mail.port=test
spring.mail.username=test
spring.mail.password=test
spring.mail.properties.mail.smtp.auth=test
spring.mail.properties.mail.smtp.ssl.enable=test

# ===== PortOne(\uC544\uC784\uD3EC\uD2B8) V1 =====
imp.code=test
imp.store_id=test
imp.api-key=test
imp.api-secret=test
imp.api-secret-v2=test
imp.channel-card=test
imp.channel-kakao=test