spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=yoonho7198@naver.com
spring.mail.password=WEZMRTU9DLX2
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

# ===== PortOne(\uC544\uC784\uD3EC\uD2B8) V1 =====
imp.code=imp81500475
imp.store_id=store-f2951fe6-cd0a-4478-8edd-76661cc42ceb
imp.api-key=6774231213273620
imp.api-secret=lVwWy2zenucoMlAJ4fuqH8PCu5lj4bbVWjgVhzvsk0aq09e9uBLIao000DcWdxTdmaUveT0B3JbBz17j
imp.api-secret-v2=WGHeF1v1wJXsWL6hFJYKhgoqRGogoPpWykU2VXfWUvt4WPF4Ve1QmTENxUi8aMSb78AYWJ2oFuhFmc9x
imp.channel-card=channel-key-cdcd1992-6293-4e38-bb9d-55928bd89061
imp.channel-kakao=channel-key-19428d65-5f22-486a-b242-7e9c3e3e8512