spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=yoonho7198@naver.com
spring.mail.password=WEZMRTU9DLX2
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

# ===== PortOne(\uC544\uC784\uD3EC\uD2B8) V1 =====
imp.code=imp81500475
imp.api-key=6774231213273620
imp.api-secret=lVwWy2zenucoMlAJ4fuqH8PCu5lj4bbVWjgVhzvsk0aq09e9uBLIao000DcWdxTdmaUveT0B3JbBz17j
imp.channel-card=channel-key-2ef568e9-3106-4b7a-9181-89ca9c6776e3
imp.channel-kakao=channel-key-780fb053-8092-4dd0-bc1b-e4a1936959ce